name: EnterpriseKind

# Any change in triggers needs to be reflected in the concurrency group.
on:
  pull_request:
    paths-ignore:
      - 'Documentation/**'
      - 'test/**'

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true

env:
  helm_chart_repo: oci://quay.io/isovalent-charts-dev/cilium
  fqdn_proxy_version: v1.14.0-rc1
  kind_version: v0.17.0
  kind_config: .github/kind-config.yaml

jobs:
  installation-and-connectivity:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          # checkout pull request head ref so that print-chart-version.sh prints the correct chart version.
          ref: ${{ github.event.pull_request.head.ref }}
          # required for git describe
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: 'enterprise/cilium-cli/go.mod'

      - name: Set up job variables
        id: vars
        run: |
          version=$(bash contrib/scripts/print-chart-version.sh)
          echo "version=${version}" >> $GITHUB_OUTPUT
          echo ${version}

      - name: Create kind cluster
        uses: helm/kind-action@dda0770415bac9fc20092cacbc54aa298604d140 # v1.8.0
        with:
          version: ${{ env.kind_version }}
          config: ${{ env.kind_config }}

      - name: Build cilium-cli
        run: |
          cd enterprise/cilium-cli
          go mod tidy
          test -z "$(git status --porcelain)" || (echo "please run 'go mod tidy' and submit your changes"; exit 1)
          make

      - name: Wait for Helm dev chart to be available
        timeout-minutes: 30
        shell: bash
        run: |
          until helm pull ${{ env.helm_chart_repo }} --version ${{ steps.vars.outputs.version }} &> /dev/null; do sleep 30s; done

      - name: Install Cilium
        run: |
          helm install -n kube-system cilium ${{ env.helm_chart_repo }} --version ${{ steps.vars.outputs.version }} --set-string extraConfig.external-dns-proxy="true"
          kubectl rollout status -n kube-system ds/cilium

      - name: Install FQDN proxy
        run: |
          helm repo add isovalent https://helm.isovalent.com
          helm repo update
          helm install -n kube-system cilium-dnsproxy isovalent/cilium-dnsproxy --version ${{ env.fqdn_proxy_version }} --set prometheus.enabled=true
          kubectl rollout status -n kube-system ds/cilium

      - name: Run enterprise tests
        run: |
          cd enterprise/cilium-cli
          ./cilium version
          ./cilium connectivity test --debug --collect-sysdump-on-failure

      - name: Cleanup
        if: ${{ always() }}
        run: |
          cd enterprise/cilium-cli
          ./cilium status
          kubectl get pods --all-namespaces -o wide
          ./cilium sysdump --output-filename cilium-sysdump-out --hubble-flows-count 10000
        shell: bash {0} # Disable default fail-fast behaviour so that all commands run independently

      - name: Upload artifacts
        if: ${{ !success() }}
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: cilium-sysdump-out.zip
          path: enterprise/cilium-cli/cilium-sysdump-*.zip
          retention-days: 5
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
